version: "3"

services:
  app:
    image: app/supreme
    container_name: supreme
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sqlsa
      - MYSQL_PASSWORD=SuperPass1
      - MYSQL_DATABASE=Supreme

  redis:
    image: redis
    container_name: redis
    command: >
      redis-server 
        --include /usr/local/etc/redis/redis.conf 
        --save 120 1 
        --loglevel warning 
        --appendonly yes 
        --maxmemory 256mb 
        --maxmemory-policy allkeys-lru
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl
    ports:
      - "6379:6379"