name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  PROJECT_PATH: 'SupremeDotnetApiTemplate.csproj'

jobs:
  deploy:
    name: 'Deploy NuGet Package'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout source'
      uses: actions/checkout@v2

    - name: 'Install .NET Core 7 SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Get version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack NuGet Package'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --cofiguration Release  --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Publish NuGet Package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --api-key ${{ secrets.NUGET_AUTH_TOKEN }}